### ISSUE TITLE
send to sqlmap, mac支持问题

### ISSUE THREAD

**Issue by WayZzz** [bit4woo/knife#12]
配置的差不多，但是点击 run sqlmap之后 只是复制了sqlmap命令，而没有调用terminal去执行，需要自己打开terminal粘贴之后执行，是不是我的姿势不对~~

另： sqlmap-request-files 参数配置不生效~~ mac下

**Comment by bit4woo** [comment]
不好意思~~，完全没有用过mac。你可以看看代码，然后提交mac下如何执行的方法给我，以便支持。感谢！

**Comment by KIMIlin997** [comment]
你好，sqlmap kali 跟parrot os都没反应。是不是只支持windows

**Comment by bit4woo** [comment]
@WayZzz mac下调试成功了，可以试试
