### ISSUE TITLE
Extension adding entries with status -1 in logger++

### ISSUE THREAD

**Issue by Neolex-Security** [bit4woo/knife#14]
Hi,
When using logger++ burp plugin and using your entension every request are sent 2 times and one of them respond with status -1
I tried to remove all options of knife to get only the right click utilities but it doesn't change anything.

Here is a screenshot of the issue : 
![image](https://user-images.githubusercontent.com/15272044/63691480-9ae0d000-c80f-11e9-8546-5f8df993b5fc.png)

I use burp v2.1.03 and knife 1.5

**Comment by bit4woo** [comment]
it's due to following code:
`message.setInterceptAction(IInterceptedProxyMessage.ACTION_FOLLOW_RULES_AND_REHOOK);`
in function:
`public void processProxyMessage(boolean messageIsRequest, IInterceptedProxyMessage message) {`
for function "Dismiss"

**Comment by Neolex-Security** [comment]
is there a way to fix it ?

**Comment by bit4woo** [comment]
the function need it, burp didn't send 2 requests in fact.
