### ISSUE TITLE
knife跟logger++冲突

### ISSUE THREAD

**Issue by cx9208** [bit4woo/knife#23]
装了knife后logger++会变成这样https://s1.ax1x.com/2020/05/03/YSRXiF.png，每一个请求都多了一个无响应的，有什么办法能兼容吗

**Comment by bit4woo** [comment]
已在如下commit中解决这个问题，会在后续版本发布。感谢关注
https://github.com/bit4woo/knife/commit/95b56ffd5ceee88916de26d088b94007fe1822f4
