### ISSUE TITLE
导入插件后，右键使用报错

### ISSUE THREAD

**Issue by pipichong** [bit4woo/knife#25]
下载的1.8版本的，导入后右键没有显示，看错误信息出现这个。
![image](https://user-images.githubusercontent.com/35160492/84473458-aed0c200-acbb-11ea-9d0b-2a8f4f47a6e6.png)
![image](https://user-images.githubusercontent.com/35160492/84473431-a1b3d300-acbb-11ea-9c2e-cf88bd95c37c.png)

**Comment by ooooojamin** [comment]
我也是一样的问题

**Comment by bit4woo** [comment]
bug已修复，感谢反馈
