### ISSUE TITLE
MAC 版本的burp1.7破解版本，发现一些bug，希望大牛关注下哈

### ISSUE THREAD

**Issue by inject2006** [bit4woo/knife#28]
1. 调用外部命令的时候java报错， empty string，或者无法调用命令，直接把url输出到了shell上
2. 尝试使用2.1版本右键没有菜单出来。
3. dismiss 无效，dismiss的url依然会收到resp

另外很欣赏您的插件Idea，希望加一个邮箱或者微信沟通联系哈。

**Comment by bit4woo** [comment]
可以给我发邮件bit4woo@163.com

**Comment by fayewong00** [comment]
dismiss功能不起作用，dismiss后网站直接打不开，请问有没有burp版本的限制，burp版本兼容性有没有测试过

**Comment by bit4woo** [comment]
dismiss有2种模式：
1、直接drop掉请求。
2、只是标记为灰色，并不进行拦截。
