### ISSUE TITLE
一个add host to scope的小bug

### ISSUE THREAD

**Issue by Conanjun** [bit4woo/knife#3]
通过插件添加的第一个host不会触发burp target的 logging out-of-scope proxy traffic id disabled,每次都得手工在scope里添加一个才能触发，然后再用插件添加就可以
![image](https://user-images.githubusercontent.com/7765655/56720401-57992680-6775-11e9-8db7-08f6ba335350.png)

**Comment by bit4woo** [comment]
没明白你描述的问题，请详细说明
