### ISSUE TITLE
win+burp2020.12.1 runSqlmap执行命令直接插入报文中

### ISSUE THREAD

**Issue by z7701858** [bit4woo/knife#30]
win+burp2020.12.1
runSqlmap功能=>repeater中点击后，会先将参数插入报文中，再启动终端
![image](https://user-images.githubusercontent.com/32709921/103397189-2f7ce000-4b72-11eb-8ec9-a3cf68c2dfef.png)
![image](https://user-images.githubusercontent.com/32709921/103397203-415e8300-4b72-11eb-8fd2-3285030a36a6.png)

**Comment by bit4woo** [comment]
下载最新版（1.9版本修复该问题），通过修改RunTerminalWithRobotInput配置项来控制它的行为：
如果启用这个选项（Enable 为true），就是模拟输入，当cmd启动速度慢了就会出现如上问题。
如果关闭这个选项（enable 为false），会采用运行bat文件的行方式启动，可以避免如上问题，但是命令行窗口就不会有命令的历史记录。
