### ISSUE TITLE
右键扩展过多，能否本插件所有的选项集中到一个复选框内？

### ISSUE THREAD

**Issue by winezer0** [bit4woo/knife#31]
右键扩展过多，导致电脑无法全部显示所有右键菜单
能否本插件所有的右键选项集中到一个一级右键菜单中内？

**Comment by winezer0** [comment]
查看了一下源码，再看了一下knife1.8的功能，发现1.8存在将所有扩展缩为一个右键菜单的选项。
因此，本issue已解决。

**Comment by bit4woo** [comment]
![image](https://user-images.githubusercontent.com/8793481/103644366-38feb180-4f91-11eb-92b9-322e0d341cb1.png)
