### ISSUE TITLE
依赖编译失败

### ISSUE THREAD

**Issue by tuhaolam** [bit4woo/knife#32]
[ERROR] Failed to execute goal on project knife: Could not resolve dependencies for project com.bit4woo.burp:knife:jar:1.8: Could not find artifact com.github.bit4woo:burp-api-common:jar:v0.1.0 in nexus-aliyun (http://maven.aliyun.com/nexus/content/groups/public

**Comment by bit4woo** [comment]
这个依赖包不存在于maven仓库中，是通过https://jitpack.io下载的，所以需要在pom.xml中添加如下内容

`	<repositories>
		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>
	</repositories>`

参见https://github.com/bit4woo/knife/blob/master/pom.xml
