### ISSUE TITLE
sqlmap，nmap 的调用问题

### ISSUE THREAD

**Issue by HighPing1667** [bit4woo/knife#33]
如果我的Windows没有本地安装或者部署SQLMAP以及NMAP，但是在安装了WSL（如kali），可以通过kali run sqlmap 或者kali run nmap 的命令来直接运行sqlmap和nmap，不知道配置怎么设置，让他通过指定命令运行，而不是去运行设置路径中的文件。

**Comment by bit4woo** [comment]
没见过你这种情况，但是命令都是拼接起来的，你可在你配置的文件前面加上”kali run “试试
