### ISSUE TITLE
不支持mac 版的burp 我点击了sqlmap nmap没反应？？

### ISSUE THREAD

**Issue by kernelzhen** [bit4woo/knife#36]
![image](https://user-images.githubusercontent.com/20443637/122786857-50cfb500-d2e7-11eb-981a-67b0a0d42d5e.png)

**Comment by lyx52888** [comment]
我也一样，不能使用，使用另一个插件就能打开，希望好哥哥(作者)解决一下

**Comment by bit4woo** [comment]
插件支持2种模式运行Nmap和SQLmap：
1、使用本地脚本文件，这种方式比较稳定，但是看不到命令的历史记录【Windows下看不到，Mac可以】
2、使用模拟输入的方式，即先打开终端，然后从剪切板粘贴进去，这种方式执行完成的命令会有历史记录。

如果运行失败，可以通过如下配置，切换到模式1。
![image](https://user-images.githubusercontent.com/8793481/128851041-2c8a6ac2-47f1-4a1f-8ecd-84b469c904e1.png)
