### ISSUE TITLE
Burpsuite v2021.8加载knife使用U2C之后无法再显示Response

### ISSUE THREAD

**Issue by cnzzr** [bit4woo/knife#39]
在Proxy的Response中点选一次 U2C之后造成 Response 标准消失，如图所示

![image](https://user-images.githubusercontent.com/239363/132295947-46f540e8-26f0-42d1-b8a3-524b2c33884f.png)

**Comment by bit4woo** [comment]
这个应该是burp的bug，之前已经反馈给了burp

**Comment by bit4woo** [comment]
![image](https://user-images.githubusercontent.com/8793481/140005469-65216bf4-937b-47c7-b6a0-67aac22f375c.png) 官方已解决这个问题，需要更新新版本。

**Comment by bit4woo** [comment]
burp最新版本下载地址： https://portswigger.net/burp/releases
