### ISSUE TITLE
关于插件的使用问题

### ISSUE THREAD

**Issue by zhengze-111** [bit4woo/knife#41]
请问knife2.0上insert xss的功能去掉了吗？为什么在使用的时候没有呢
![f48e8792f72038e5dc728eeb1d1f147](https://user-images.githubusercontent.com/97343388/148944177-9de02603-8dd5-4b36-9087-fe63f43aa8f8.png)
？

**Comment by bit4woo** [comment]
变成了【Insert Payload For All】：
原来是只支持将插入XSS Payload插入所有非数字的参数值；现在是可以将任意的Payload插入
