### ISSUE TITLE
请求包自动修改功能无法修改GET请求为POST请求

### ISSUE THREAD

**Issue by baibainmb** [bit4woo/knife#43]
需求为repeater和intruder模块中修改全部的GET请求为POST请求
但是
2、自动新增或者修改
的Action_Add_Or_Replace_Header无法匹配到GET/POST请求头
期待作者能够对此进行更新

**Comment by bit4woo** [comment]
请求方法的变化，往往涉及到整个数据包的变化，比如参数位置从URL变化到body中。单纯通过匹配替换个人认为不是好的实现方式。

**Comment by baibainmb** [comment]
> 请求方法的变化，往往涉及到整个数据包的变化，比如参数位置从URL变化到body中。单纯通过匹配替换个人认为不是好的实现方式。

嗯 或者能否通过burp内置的Change request method实现 昨天测试中第一次发现站点限制了请求方式 不清楚其它前辈是如何解决这个问题的 我通过burp的proxy模块能对部分请求方式替换 而repeater和intruder模块暂不支持 于是我找到了knife。

**Comment by bit4woo** [comment]
Repeater是支持在POST和GET间互相切换的。Intruder中，你也可以在Repeater中变化后发送过去。不是很理解你遇到的情况到底是什么场景。如果可以，请尽可能描述场景和目的。

**Comment by baibainmb** [comment]
嗯嗯 感谢作者的帮助
