### ISSUE TITLE
大佬能做成和hack bar一样的分层结构么？

### ISSUE THREAD

**Issue by NeverDieSuddenly** [bit4woo/knife#51]
大佬能做成和hack bar一样的分层结构么？

**Comment by bit4woo** [comment]
高版本burp已经是自动根据插件名称归类二级菜单了，再分层感觉层级太多不合适了

**Comment by NeverDieSuddenly** [comment]
具体是咋弄的呢? 例如我要生成一个这样的 可以实现么
xss 名称
&nbsp;xss 反射型
&nbsp; payloads
&nbsp;xss 存储型
&nbsp; payloads




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bit4woo/knife"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月18日(星期五) 下午5:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bit4woo/knife] 大佬能做成和hack bar一样的分层结构么？ (Issue #51)





 
高版本burp已经是自动根据插件名称归类二级菜单了，再分层感觉层级太多不合适了
