### ISSUE TITLE
V 2.1  unicode 解码乱码 

### ISSUE THREAD

**Issue by zzqsmile** [bit4woo/knife#54]
<img width="619" alt="image" src="https://user-images.githubusercontent.com/38462538/203013727-e8f33bc1-7570-48f1-b494-126e5b6a520e.png">

**Comment by winezer0** [comment]
已尝试进行修复,请参考合并pull requests

**Comment by bit4woo** [comment]
已修复，感谢反馈 https://github.com/bit4woo/knife/commit/aab4e4e71998883f5c2d7202ac17af79bbb871a6
