### ISSUE TITLE
能不能改造成任意工具的调用？

### ISSUE THREAD

**Issue by winezer0** [bit4woo/knife#60]
能不能基于sqlmap的实现，改造成任意工具的命令行调用

相关输入参数可以用变量代替：
如http_packet 报文、proto 协议、 host请求头、url等

可参考bytebutcher/burp-send-to: Adds a customizable "Send to..."-context-menu to your BurpSuite.
https://github.com/bytebutcher/burp-send-to

**Comment by bit4woo** [comment]
体验了一下你推荐的项目，这个工具感觉不错，为什么不直接使用他的工具呢？

**Comment by winezer0** [comment]
因为knife也提供了类似的功能（自定义增加菜单+命令执行），并且knife是我电脑上的必备插件，如果我再安装send-to就会有一些功能上的冗余. 因此想要建议大佬把这个自定义命令的功能带上去。

也不用支持完全的send-to-功能，可以仅实现部分常用报文即可。
