### ISSUE TITLE
找不到符号 [ERROR]   符号: 变量 SystemUtils

### ISSUE THREAD

**Issue by LHXHL** [bit4woo/knife#62]
burp包里并没有SystemUtils类
<img width="1094" alt="image" src="https://github.com/bit4woo/knife/assets/44888589/5978382b-8da7-4402-9a0e-e340e68bdba6">
<img width="756" alt="image" src="https://github.com/bit4woo/knife/assets/44888589/a9aa21e4-d1d7-4517-8228-c81c0b5ce8cb">

**Comment by bit4woo** [comment]
https://github.com/bit4woo/knife/issues/55

**Comment by LHXHL** [comment]
> #55

谢谢，之前用的备选方案二，改成方案一可以了
