### ISSUE TITLE
希望chinese tab 能够支持换行

### ISSUE THREAD

**Issue by winezer0** [bit4woo/knife#67]
当前的是 面板 过长会显示 滚动条，内容多的时候看起来很复杂

如果能不把内置的换行功能也放在面板上就好了

![image](https://github.com/bit4woo/knife/assets/46115146/524c383e-ec12-4c40-a23c-a833a81a382b)

**Comment by cirts** [comment]
确实有这个问题，横着有滚动条，看着不方便
![image](https://github.com/bit4woo/knife/assets/40534904/f9b33812-b520-436d-b674-b435d2cb2cba)

**Comment by cirts** [comment]
和Pretty一样能格式化就更好了
![image](https://github.com/bit4woo/knife/assets/40534904/0754b7d2-c4cf-4980-8e08-876e7556f73b)

**Comment by bit4woo** [comment]
2.3版本已实现
https://github.com/bit4woo/knife/releases/tag/v2.3

**Comment by winezer0** [comment]
强大

**Comment by winezer0** [comment]
感谢感谢，大佬NB
