### ISSUE TITLE
latest knife enable dismiss can't auto refresh http history

### ISSUE THREAD

**Issue by passwa11** [bit4woo/knife#85]
when enable dismiss and hide items without responses
![image](https://github.com/bit4woo/knife/assets/112363374/a6ebdce7-6c04-4e9b-99e3-ab7ac71245a5)
![image](https://github.com/bit4woo/knife/assets/112363374/7a1c1d08-435e-47c5-8e6c-7f31d87bd898)

http history not refresh anymore
but when i uncheked the [hide items without responses] it's refresh work well .

**Comment by bit4woo** [comment]
是否有详细报错信息

**Comment by passwa11** [comment]
not any errors

**Comment by XF-FS** [comment]
This is an issue with the Burp version. Currently, I am in the 2024.1.1 version and there is no problem. In the 2024.04 version, there will be no refresh, and closing the plugin will also be the same

**Comment by passwa11** [comment]
> This is an issue with the Burp version. Currently, I am in the 2024.1.1 version and there is no problem. In the 2024.04 version, there will be no refresh, and closing the plugin will also be the same

yep,u are right! upgrade burp to 2024.5.it's work well again.
